// Vale na Conta – GitHub OAuth backend. Deploy as a Cloudflare Worker.
// Required secrets: GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET, SESSION_KEY (32+ random characters).
const OWNER='gmachado0',REPO='vale-na-conta';
const PUBLIC_ADMIN='https://gmachado0.github.io/vale-na-conta/admin-oauth.html';
const SESSION_DAYS=7;
const response=(body,status=200,headers={})=>new Response(typeof body==='string'?body:JSON.stringify(body),{status,headers:{'Cache-Control':'no-store','Content-Type':typeof body==='string'?'text/plain; charset=utf-8':'application/json; charset=utf-8',...headers}});
const redirect=(url,headers={})=>new Response(null,{status:302,headers:{Location:url,'Cache-Control':'no-store',...headers}});
const cookie=(name,value,days=0)=>name+'='+encodeURIComponent(value)+'; Path=/; Secure; HttpOnly; SameSite=Lax'+(days?'; Max-Age='+Math.round(days*86400):'; Max-Age=0');
const fromCookie=(request,name)=>{const m=(request.headers.get('Cookie')||'').match(new RegExp('(?:^|;\\s*)'+name+'=([^;]+)'));return m?decodeURIComponent(m[1]):''};
const enc=new TextEncoder(),dec=new TextDecoder();
const b64=b=>{const bytes=new Uint8Array(b);let out='';for(let i=0;i<bytes.length;i+=8192)out+=String.fromCharCode(...bytes.slice(i,i+8192));return btoa(out).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
const unb64=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4)),c=>c.charCodeAt(0));
async function key(env){const bits=await crypto.subtle.digest('SHA-256',enc.encode(env.SESSION_KEY));return crypto.subtle.importKey('raw',bits,{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function seal(data,env){const iv=crypto.getRandomValues(new Uint8Array(12));const bytes=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(env),enc.encode(JSON.stringify(data)));return b64(iv)+'.'+b64(bytes)}
async function unseal(text,env){try{const [iv,data]=text.split('.');if(!iv||!data)return null;const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(iv)},await key(env),unb64(data));return JSON.parse(dec.decode(plain))}catch{return null}}
async function api(url,token,options={}){const r=await fetch(url,{...options,headers:{'Accept':'application/vnd.github+json','Authorization':'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'ValeNaConta-Admin/1.0',...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error((data.message||'GitHub API error')+' ('+r.status+')');return data}
async function session(request,env){const data=await unseal(fromCookie(request,'vnc_session'),env);if(!data||data.exp<Date.now()||data.login!==OWNER||!data.token)return null;return data}
const fileUrl='https://api.github.com/repos/'+OWNER+'/'+REPO+'/contents/catalogo-oficial.json';
function catalogOK(data){if(!data||data.schema!==1||!Array.isArray(data.restaurants)||data.restaurants.length>100)return false;const ids=new Set();for(const r of data.restaurants){if(!r||!/^([a-z0-9]{1,64})$/.test(r.id||'')||ids.has(r.id)||typeof r.name!=='string'||!r.name.trim()||r.name.length>70||!Array.isArray(r.meals)||r.meals.length>500)return false;ids.add(r.id);for(const m of r.meals){if(m===null)continue;if(!Array.isArray(m)||typeof m[0]!=='string'||!m[0].trim()||m[0].length>100||!Number.isFinite(Number(m[1]))||Number(m[1])<0||Number(m[1])>10000)return false}}return true}
export default {async fetch(request,env){
 const url=new URL(request.url),origin=url.origin,path=url.pathname;
 if(!env.GITHUB_CLIENT_ID||!env.GITHUB_CLIENT_SECRET||!env.SESSION_KEY)return response({error:'Configure os três secrets do Worker.'},503);
 if(path==='/'||path==='/admin'){if(request.method!=='GET')return response('Method not allowed',405);const up=await fetch(PUBLIC_ADMIN,{headers:{'Accept':'text/html'}});if(!up.ok)return response('Admin HTML não publicado',503);return new Response(up.body,{status:200,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self'; img-src 'self' data:; form-action 'self'; frame-ancestors 'none'; base-uri 'none'",'Referrer-Policy':'no-referrer'}})}
 if(path==='/auth/login'){if(request.method!=='GET')return response('Method not allowed',405);const state=b64(crypto.getRandomValues(new Uint8Array(32)));const github=new URL('https://github.com/login/oauth/authorize');github.searchParams.set('client_id',env.GITHUB_CLIENT_ID);github.searchParams.set('redirect_uri',origin+'/auth/callback');github.searchParams.set('scope','public_repo');github.searchParams.set('state',state);github.searchParams.set('allow_signup','false');return redirect(github.href,{'Set-Cookie':cookie('vnc_state',state,0.1)})}
 if(path==='/auth/callback'){if(request.method!=='GET')return response('Method not allowed',405);const state=url.searchParams.get('state')||'',expected=fromCookie(request,'vnc_state');if(!state||!expected||state!==expected||!url.searchParams.get('code'))return response('OAuth state inválido. Inicie o login novamente.',400);
 const form=new URLSearchParams({client_id:env.GITHUB_CLIENT_ID,client_secret:env.GITHUB_CLIENT_SECRET,code:url.searchParams.get('code'),redirect_uri:origin+'/auth/callback'});
 const exchange=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/x-www-form-urlencoded'},body:form});const result=await exchange.json();if(!result.access_token)return response('Falha no login GitHub.',403);
 let phase='GitHub profile';
 try{const profile=await api('https://api.github.com/user',result.access_token);if(profile.login!==OWNER)return response('Conta GitHub não autorizada para administrar este painel.',403);
 phase='repository permissions';
 const repo=await api('https://api.github.com/repos/'+OWNER+'/'+REPO,result.access_token);if(!repo.permissions?.push)return response('A autenticação funcionou, mas a conta não tem permissão de escrita no repositório.',403);
 phase='session encryption';
 const secure=await seal({login:profile.login,token:result.access_token,exp:Date.now()+SESSION_DAYS*86400000},env);
 const headers=new Headers({Location:origin+'/admin','Cache-Control':'no-store'});headers.append('Set-Cookie',cookie('vnc_session',secure,SESSION_DAYS));headers.append('Set-Cookie',cookie('vnc_state',''));return new Response(null,{status:302,headers})}catch(error){console.error('OAuth callback failed at',phase,error?.name||'UnknownError');return response('Erro ao concluir login na etapa: '+phase+'. Verifique os logs do Worker em Observability. Código: '+(error?.name||'Error'),403)}}
 if(path==='/api/session'){const user=await session(request,env);return response({authenticated:!!user,login:user?.login||null})}
 if(path==='/auth/logout'){if(request.method!=='POST')return response('Method not allowed',405);if(request.headers.get('Origin')!==origin)return response('Forbidden',403);return response({ok:true},200,{'Set-Cookie':cookie('vnc_session','')})}
 if(path==='/api/catalog'){const user=await session(request,env);if(!user)return response({error:'Não autorizado'},401);
 if(request.method==='GET'){try{const file=await api(fileUrl+'?ref=main',user.token);return response({sha:file.sha,content:dec.decode(unb64(file.content.replace(/\s/g,'').replace(/\+/g,'-').replace(/\//g,'_')))})}catch(e){return response({error:e.message},502)}}
 if(request.method==='PUT'){if(request.headers.get('Origin')!==origin)return response({error:'Origem não autorizada'},403);if(!(request.headers.get('Content-Type')||'').startsWith('application/json'))return response({error:'Content-Type inválido'},415);const raw=await request.text();if(raw.length>600000)return response({error:'Catálogo muito grande'},413);let body;try{body=JSON.parse(raw)}catch{return response({error:'JSON inválido'},400)}if(!body?.sha||!catalogOK(body.catalog))return response({error:'Dados de publicação inválidos'},400);
 try{const current=await api(fileUrl+'?ref=main',user.token);if(current.sha!==body.sha)return response({error:'O catálogo mudou. Recarregue antes de publicar.'},409);const content=b64(enc.encode(JSON.stringify(body.catalog,null,2)));const result=await api(fileUrl,user.token,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Atualiza catálogo oficial pelo painel OAuth',content,sha:body.sha,branch:'main'})});return response({ok:true,sha:result.content?.sha})}catch(e){return response({error:e.message},502)}}}
 return response('Not found',404);
}};